# Generated by Django 4.0.4 on 2022-05-09 19:02

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_keymanagement_alter_customerdetails_updated_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='keymanagement',
            name='head_office',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='customerdetails',
            name='updated_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 9, 19, 2, 52, 245757, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='discountpointsystem',
            name='updated_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 9, 19, 2, 52, 245357, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='keymanagement',
            name='activated_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 5, 9, 19, 2, 52, 246332, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='rewardpointsystem',
            name='updated_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 9, 19, 2, 52, 244559, tzinfo=utc)),
        ),
    ]
