# Generated by Django 4.0.4 on 2022-05-29 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_alter_customerdetails_updated_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Packages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(blank=True, max_length=255)),
                ('basic_price', models.IntegerField(default=0)),
                ('final_price', models.IntegerField(default=0)),
                ('link', models.CharField(blank=True, max_length=1000)),
            ],
        ),
        migrations.AddField(
            model_name='keymanagement',
            name='access_token',
            field=models.CharField(blank=True, default='ZV201U2QweHVUakJaVjA1eVdUTkJkVmt5T1hRPQ==', max_length=300),
        ),
        migrations.AddField(
            model_name='keymanagement',
            name='branch',
            field=models.CharField(blank=True, default='twinbook', max_length=30),
        ),
        migrations.AddField(
            model_name='keymanagement',
            name='drive_folder',
            field=models.CharField(blank=True, default='OWkVoa2NHSnVUbXBpTWxKc1kyazFNRnBYVG04PQ==', max_length=300),
        ),
        migrations.AddField(
            model_name='keymanagement',
            name='local_path',
            field=models.CharField(blank=True, default='OU1ZaR1FWWjVUa1pLUmtsc1ZrWTFXZz09', max_length=300),
        ),
        migrations.AddField(
            model_name='keymanagement',
            name='passkey',
            field=models.CharField(blank=True, default='twinbook', max_length=30),
        ),
    ]
